<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.18362.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miracast.Receiver\Miracast.Receiver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
  </ItemGroup>

</Project>
