<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miracast.Receiver\Miracast.Receiver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.4" />
    <PackageReference Include="Tmds.DBus" Version="0.95.0" />
  </ItemGroup>

</Project>
